JOIN_SEPARATORS = "._-*+~|"

LEET_MAP = {
    "0": "o",
    "1": "i",
    "3": "e",
    "4": "a",
    "5": "s",
    "7": "t",
    "9": "g",
    "@": "a",
    "$": "s",
}

TEENCODE_MAP = {
    "k": "không",
    "ko": "không",
    "kg": "không",
    "kh": "không",
    "hk": "không",
    "hok": "không",
    "khg": "không",
    "khong": "không",
    "hong": "không",
    "đc": "được",
    "dc": "được",
    "đk": "được",
    "dk": "được",
    "duoc": "được",
    "j": "gì",
    "z": "vậy",
    "dz": "vậy",
    "v": "vậy",
    "r": "rồi",
    "ròi": "rồi",
    "roi": "rồi",
    "qa": "quá",
    "wa": "quá",
    "qá": "quá",
    "quá": "quá",
    "mk": "mình",
    "mik": "mình",
    "mjk": "mình",
    "mnh": "mình",
    "b": "bạn",
    "bn": "bạn",
    "bme": "bố mẹ",
    "bmẹ": "bố mẹ",
    "mn": "mọi người",
    "mng": "mọi người",
    "ng": "người",
    "ny": "người yêu",
    "gđ": "gia đình",
    "gd": "gia đình",
    "ae": "anh em",
    "ace": "anh chị em",
    "vk": "vợ",
    "ck": "chồng",
    "bt": "bình thường",
    "bth": "bình thường",
    "bjo": "bây giờ",
    "bgio": "bây giờ",
    "bjh": "bây giờ",
    "h": "giờ",
    "hnay": "hôm nay",
    "hqua": "hôm qua",
    "ntn": "như thế nào",
    "nma": "nhưng mà",
    "nhma": "nhưng mà",
    "ns": "nói",
    "nt": "nhắn tin",
    "tl": "trả lời",
    "ib": "nhắn riêng",
    "cmt": "bình luận",
    "cx": "cũng",
    "lm": "làm",
    "lun": "luôn",
    "lươn": "luôn",
    "nhiu": "nhiều",
    "nhìu": "nhiều",
    "iu": "yêu",
    "mún": "muốn",
    "mun": "muốn",
    "muk": "muốn",
    "sốg": "sống",
    "sog": "sống",
    "bùn": "buồn",
    "bun": "buồn",
    "chán": "chán",
    "đag": "đang",
    "dag": "đang",
    "đt": "điện thoại",
    "dt": "điện thoại",
    "sđt": "số điện thoại",
    "sdt": "số điện thoại",
    "cty": "công ty",
    "xl": "xin lỗi",
    "dth": "dễ thương",
    "vs": "với",
    "tks": "cảm ơn",
    "thks": "cảm ơn",
    "cam on": "cảm ơn",
    "stress": "căng thẳng",
}
